### ISSUE TITLE
update pypi version

### ISSUE THREAD

**Issue by mgrandi** [manicmaniac/sqlalchemy-repr#3]
Hello, it seems that the most recent commit isn't on pypi: 

https://github.com/manicmaniac/sqlalchemy-repr/commit/6545e495f4dde1824304b296acb42bd0aaeeb629

https://pypi.org/project/sqlalchemy-repr/

If you have time, can you bump the version and upload a new version to pypi? thanks

**Comment by manicmaniac** [comment]
@mgrandi Thanks for reminding me :pray:
I will do it in a couple of days :+1:

**Comment by manicmaniac** [comment]
Released https://pypi.org/project/sqlalchemy-repr/0.0.2/

**Comment by mgrandi** [comment]
Hi, its been a while, but I tried to update to the latest version but it doesn't update because of how you built it: https://pypi.org/simple/sqlalchemy-repr/

note how the 0.0.2 version is only for mac os x, because I'm assuming you built the release using `python3 setup.py bdist` and then uploaded that

to make it so its 'generic' for all operating systems/ architectures and whatnot, you should build it as a wheel,  which can be done by doing `pip3 install wheel` and then `python3 setup.py bdist_wheel` and then using twine or whatever is used now to upload the release to pypi

thanks again!

**Comment by manicmaniac** [comment]
@mgrandi 

Thank you for the detailed instruction and sorry 😓 

I just uploaded 0.0.2 wheel to PyPI.
https://pypi.org/project/sqlalchemy-repr/0.0.2/#files

**Comment by mgrandi** [comment]
thanks! that worked and i can install version 0.0.2
